FROM nvcr.io/nvidia/l4t-base:r32.6.1

WORKDIR /usr/src/app

RUN apt update \
    && apt install -y python3.8 \
    && apt install -y python3-pip \
    && python3.8 -m pip install --upgrade pip

COPY . .
RUN python3.8 -m pip install --no-cache-dir .

CMD ["uvicorn", "controller.main:app", "--host", "0.0.0.0", "--port", "80"]