name: Build and push docker image for config daemon

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push config-daemon
        uses: docker/build-push-action@v2
        with:
          context: ./config_daemon
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/config-daemon:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/config-daemon:latest
      -
        name: Build and push inference-server
        uses: docker/build-push-action@v2
        with:
          context: ./inference_server
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/inference-server:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/inference-server:latest
